### ISSUE TITLE
Add "Delete", "Done" and increment, decrement button to change DSL in the edit panel.

### ISSUE THREAD

**Issue by ayushranjan-planetria** [ShoppinPal/warehouse#160] opened 2015-07-24 11:24 UTC

**Comment by elbrando** [comment] 2015-07-24 15:29
Needs to be in Fulfillment and Receiving, too. Any line item edits.

**Comment by pulkitsinghal** [comment] 2015-07-24 15:32
@elbrando - sure, once the clarion team helps us setup a layout for the manager's edit row specifically ... I'll take over and reproduce it for all the other ones and wire it up to work.

**Comment by pulkitsinghal** [comment] 2015-07-25 00:01
![screen shot 2015-07-24 at 6 45 28 pm](https://cloud.githubusercontent.com/assets/821963/8886808/31a56d1c-3236-11e5-94c1-daee2e0834f8.png)

The layout is wrong, the delete button is supposed to be floated to the left of Desired Stock Level and the done button is supposed to be floated to the right of Order Qty.

But instead they are currently stacked on top of each other ... and on the bottom of the rest of the controls.

**Comment by pulkitsinghal** [comment] 2015-07-25 00:30
@ayushranjan-planetria I had to `rebase` in order to bring the `feature/issue_160` branch up to date before tweaking.

Someone (you or supriya?) needs to get the done button wired up such that it behave the same way as when the user taps outside the edit row ... because we want to unbind either the `mousedown` or `touchstart` events and then call `dismissEdit` method.

@srisub - I'll work on wiring the delete button, the branch for all this work can be found here: https://github.com/ShoppinPal/warehouse/commits/feature/issue_160

**Comment by pulkitsinghal** [comment] 2015-07-26 00:34
@elbrando - does the delete button only apply to `pending` rows? or should it also be available for `completed` rows?

**Comment by pulkitsinghal** [comment] 2015-07-26 00:44
@srisub I have pulled the buttons to the left and right but they are still not in the same row as the rest of the editable fields. If this is acceptable then that's fine ... if not then let @ayushranjan-planetria and team know what more to do. cc @elbrando 

![screen shot 2015-07-25 at 7 43 38 pm](https://cloud.githubusercontent.com/assets/821963/8892007/9130c194-3305-11e5-8d40-23f724464831.png)

**Comment by srisub** [comment] 2015-07-26 06:46
@pulkitsinghal this looks good, I don't think @ayushranjan-planetria and team need to work on this any further, unless @elbrando wants something different

**Comment by pulkitsinghal** [comment] 2015-07-26 21:27
Here are the tests we need to run on the manager report (`/#/store-report-manager/:reportId`) page:

1. Swipe (right-to-left / R2L) to edit a row but don't change anything
  1. tap outside
    1. expected results
      1. row reverts back from the editable to its view-only state and does not disappear from view
      1. no changes in Vend
      1. no changes in backend (currently MongoDB)
      1. no changes in the UI of the page
  1. click `Done` button
    1. expected results
      1. row disappears from view and can be seen as the top most row after clicking the `Show Completed` button
      1. a new consignment product row should be added to the consignment in Vend
      1. the existing `StockOrderLineitemModel` row in the backend (currently MongoDB) should be updated to:
        1. track values from Vend in `vendConsignmentProductId` and `vendConsignmentProduct` fields
        1. it should also have its `state` field marked as `complete`

1. Swipe (right-to-left / R2L) to edit a row and change only the `Desired Stock Level` (DSL)
  1. tap outside
    1. expected results
      1. row reverts back from the editable to its view-only state and does not disappear from view. It should reflect the change in DSL.
      1. the product in Vend should have an updated `Re-order point` field for the outlet being used
      1. the consignment in Vend should not have any changes, yet
      1. the existing `StockOrderLineitemModel` row in the backend (currently MongoDB) should see:
        1. an updated value in its `desiredStockLevel` field
  1. click `Done` button
    1. expected results
      1. row disappears from view and can be seen as the top most row after clicking the `Show Completed` button
      1. the product in Vend should have an updated `Re-order point` field for the outlet being used
      1. a new consignment product row should be added to the consignment in Vend
      1. the existing `StockOrderLineitemModel` row in the backend (currently MongoDB) should be updated to:
        1. track values from Vend in `vendConsignmentProductId` and `vendConsignmentProduct` fields
        1. it should also have its `state` field marked as `complete`
        1. it should also have its `desiredStockLevel` updated

1. Swipe (right-to-left / R2L) to edit a row and change any editable field other than the `Desired Stock Level` (DSL)
  1. *tbd...*

**Comment by pulkitsinghal** [comment] 2015-07-26 21:49
@srisub - once you sanity test this feature for the manager report, I can get started on wiring it to other pages, where it might make sense, as well.

**Comment by srisub** [comment] 2015-07-29 00:09
@pulkitsinghal sanity tested (except the Mongo impact). Only discrepancy I can't figure out is the stock level in Vend Vs what shows up in the report. See attached. 
<img width="467" alt="screenshot 2015-07-28 18 35 41" src="https://cloud.githubusercontent.com/assets/1392314/8947074/26394718-355c-11e5-9038-85e320300a91.png">

![](https://s3.amazonaws.com/uploads.hipchat.com/48505/326418/PARSKlb63WDuo3C/upload.png)

**Comment by srisub** [comment] 2015-07-29 18:26
Clarifying Q&A (over hipchat):

1) Do u want to be able to delete from the show completed view for managers? 
2) Do you want the delete for warehouse to be
- visual only (i.e. it will come back on a page reload), or
- visual + survive page reload, or
- visual + survive page reload + delete from Vend+Mongo? Deleting from mongo means less reporting data from the perspective of what a manager ordered and what a warehouse couldn’t fulfill.
3) Would a done button be useful for warehouse folks in edit mode? Naming suggestions: instead of Done can we call ‘Boxed’ or something else? 
4) Want a Done button button in the receiver edit mode? Here we could name it ‘Unboxed’ or anything better you can come up with. 
5) Is there a use case to have the Delete button in the Receiver editable row? 
6) Pulkit found it annoying that the editable row on the manager page was dismissed if he scrolled while editing the comments area for one reason or another … so just for the manager page he  implemented a solution where scrolling does not dismiss the editable row. Would you prefer this change to be rolled back or would you want it to be incorporated into the warehouse and receiver pages also?

=====Answers=====
2) I want delete from warehouse report to remove and stay removed from the report but have full data preservation. That data is super valuable.
1) yes
4) Yes, Unboxed sounds good.
6) Yes, implement across other pages.
3) No
5) No

**Comment by pulkitsinghal** [comment] 2015-07-30 14:35
@srisub:
> 1) Do u want to be able to delete from the show completed view for managers? Yes!

... is available for testing, please check DB(mongo) and Vend to validate as well

**Comment by srisub** [comment] 2015-07-30 15:12
Verified!

**Comment by pulkitsinghal** [comment] 2015-07-30 16:20
@srisub:
> 2) I want delete from warehouse report to remove and stay removed from the report but have full data preservation. That data is super valuable.

... is available for testing ... nothing is removed from mongo or vend, page refreshes honor pseudo-deleted rows

**Comment by srisub** [comment] 2015-07-30 21:30
@pulkitsinghal @elbrando verified warehouse delete: nothing is removed from mongo or vend, page refreshes honor pseudo-deleted rows

**Comment by pulkitsinghal** [comment] 2015-07-30 23:03
@srisub - (3) & (5) are no-ops and I'm done with (6) for the warehouse page ... still need to work on (4) and (6) for receiver page ... but you can finish the testing for the `warehouse-report` page if you'd like.

**Comment by pulkitsinghal** [comment] 2015-07-30 23:08
(6) is done for `store-receiver-report` page too!

**Comment by pulkitsinghal** [comment] 2015-07-30 23:25
(7) maybe worth fixing the fact that manager comments from "before order submission" don't show up in receiver's editable row as read-only

**Comment by pulkitsinghal** [comment] 2015-07-31 13:18
@srisub (4), (6) and (7) are all done and ready for testing!

**Closed** 2015-09-28 12:32 UTC
Labels: enhancement
